name: zip feeds

on:
   workflow_dispatch:
#   push:
#     branches:
#     - master
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: zip files
        run: zip -r myzip1.zip . --exclude 'Jenkinsfile'
#           - zip release/myzip.zip .
#       - uses: papeloto/action-zip@v1
#         with:
#           files: .
#           dest: result.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
