name: uploadartifact

on:
   workflow_dispatch:
#   push:
#     branches:
#     - master
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Directory
        run: mkdir _build
#       - name: zip files
#         run: zip -r myzip1.zip . --exclude 'Jenkinsfile'
#           - zip release/myzip.zip .
#       - uses: papeloto/action-zip@v1
#         with:
#           files: .
#           dest: result.zip
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "./_build"  
#           path: ${{ github.workspace }}/myzip1.zip
